name: Schedule Test

on:
  schedule:
    - cron: "7/10 * * * *"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Test scheduler
        run: |
          echo "Schedule fired"
          date -u
